#!/usr/bin/env python3
"""向 i18n.js zh 块插入 266 个新键"""
import re

I18N_FILE = r'D:\phpstudy_pro\WWW\jingtu-web\public\js\i18n.js'

with open(I18N_FILE, 'r', encoding='utf-8') as f:
    content = f.read()

keys = {
    # events
    'events.month_1': "'一月'", 'events.month_2': "'二月'", 'events.month_3': "'三月'",
    'events.month_4': "'四月'", 'events.month_5': "'五月'", 'events.month_6': "'六月'",
    'events.month_7': "'七月'", 'events.month_8': "'八月'", 'events.month_9': "'九月'",
    'events.month_10': "'十月'", 'events.month_11': "'十一月'", 'events.month_12': "'十二月'",
    'events.day_sun': "'日'", 'events.day_mon': "'一'", 'events.day_tue': "'二'",
    'events.day_wed': "'三'", 'events.day_thu': "'四'", 'events.day_fri': "'五'", 'events.day_sat': "'六'",
    'events.count_events': "'{n}个活动'",
    'events.no_events': "'暂无活动'",
    'events.loading': "'加载中...'",
    'events.load_failed': "'加载失败'",
    'events.public': "'🌐 公开'",
    'events.member_only': "'🔒 成员专属'",
    'events.sign_in': "'签到'",
    'events.signed': "'✅ 已签到'",
    'events.not_signed': "'⬜ 未签到'",
    'events.delete': "'🗑️ 删除'",
    'events.edit': "'✏️ 编辑'",
    'events.title_time_required': "'请填写活动标题和时间'",
    'events.title_required': "'活动标题不能为空'",
    'events.start_time_required': "'活动开始时间不能为空'",
    'events.end_time_required': "'活动结束时间不能为空'",
    'events.updated': "'活动已更新'",
    'events.deleted': "'活动已删除'",
    'events.created': "'活动已发布'",
    'events.create_failed': "'活动发布失败'",
    'events.unpublished': "'活动已取消发布'",
    'events.comment_deleted': "'评论已删除'",
    'events.delete_failed': "'删除失败'",
    'events.op_failed': "'操作失败'",
    'events.confirm_delete_comment': "'确定删除此评论？'",
    'events.confirm_sign_all': "'标记该活动全员签到？'",
    'events.sign_all_ok': "'全员签到成功！'",
    'events.sign_recorded': "'签到已记录'",
    'events.no_comments': "'暂无评论'",
    'events.no_signups': "'暂无报名'",
    'events.no_signins': "'暂无签到'",
    'events.qr_signin': "'扫码签到'",
    'events.qr_title': "'签到二维码'",
    'events.qr_label': "'📱 签到二维码'",
    'events.start_time': "'📅 开始时间：'",
    'events.end_time': "'📅 结束时间：'",
    'events.location': "'📍 地点：'",
    'events.signed_up': "'👥 已报名'",
    'events.signed_in': "'👥 已签到'",
    'events.participants': "'{n} 人参加'",
    'events.participants_limit': "'{n} 人上限'",
    'events.signed_up_count': "'{n} 人已报名'",
    'events.signed_in_count': "'{n} 人已签到'",
    'events.start_label': "'📅 开始'",
    'events.end_label': "'📅 结束'",
    'events.location_label': "'📍 地点'",
    # profile_page
    'profile_page.loading': "'加载中...'",
    'profile_page.no_content': "'暂无内容'",
    'profile_page.edit_profile': "'✏️ 编辑资料'",
    'profile_page.new_album': "'📷 新建相册'",
    'profile_page.upload_video': "'🎬 上传视频'",
    'profile_page.uploading': "'上传中...'",
    'profile_page.uploading_file': "'上传文件中...'",
    'profile_page.processing': "'处理中...'",
    'profile_page.confirm_delete_album': "'确定删除该相册？此操作不可恢复。'",
    'profile_page.confirm_delete_video': "'确定删除该视频？'",
    'profile_page.public': "'🌍 公开'",
    'profile_page.member': "'👥 成员'",
    'profile_page.private': "'🔒 私密'",
    'profile_page.unknown_user': "'未知用户'",
    'profile_page.unnamed_video': "'未命名视频'",
    'profile_page.no_bio': "'尚未填写个人简介...'",
    'profile_page.avatar_updated': "'头像已更新'",
    'profile_page.avatar_upload_failed': "'头像上传失败'",
    'profile_page.profile_updated': "'资料已更新'",
    'profile_page.update_failed': "'更新失败'",
    'profile_page.name_required': "'姓名不能为空'",
    'profile_page.album_created': "'相册已创建'",
    'profile_page.album_deleted': "'相册已删除'",
    'profile_page.video_uploaded': "'视频已上传'",
    'profile_page.video_deleted': "'视频已删除'",
    'profile_page.load_failed': "'加载失败'",
    # album
    'album.all_categories': "'全部分类'",
    'album.no_photos': "'暂无照片'",
    'album.no_desc': "'无描述'",
    'album.liked': "'已点赞'",
    'album.like_failed': "'点赞失败'",
    'album.link_copied': "'链接已复制'",
    'album.batch_delete': "'批量删除'",
    'album.trash_empty': "'回收站空空如也'",
    'album.uploader': "'上传者：'",
    'album.restore': "'↩ 恢复'",
    'album.permanent_delete': "'🗑 永久删除'",
    'album.enter_category_name': "'请输入新分类名称：'",
    'album.no_category_to_delete': "'没有可删除的分类'",
    'album.select_category_delete': "'选择要删除的分类：'",
    'album.delete_category_warn': '\'该分类下的照片将移至"未分类"。\'',
    'album.confirm_batch_delete': '\'确定删除所选照片？（会移入回收站）\'',
    'album.confirm_delete_category': '\'确定删除以下分类？该分类下的照片将移至"未分类"。\'',
    'album.category_deleted': "'分类已删除'",
    'album.name_required': "'名称不能为空'",
    'album.no_announcements': "'暂无公告'",
    'album.delete': "'删除'",
    'album.batch_delete_btn': "'🗑️ 批量删除'",
    'album.confirm_batch_delete_n': '\'确定删除所选 {n} 张照片？（会移入回收站）\'',
    'album.confirm_delete_categories': '\'确定删除以下分类？该分类下的照片将移至"未分类"。\'',
    # profile
    'profile.motto_saved': "'签名已保存'",
    'profile.bio_saved': "'简介已保存'",
    'profile.avatar_updated': "'头像已更新'",
    'profile.avatar_switched_vrc': "'已切换为 VRChat 头像'",
    'profile.update_failed': "'更新失败'",
    'profile.confirm_remove_avatar': "'确定移除头像？'",
    'profile.avatar_removed': "'头像已移除'",
    'profile.enter_vrc_username': "'请输入 VRChat 用户名'",
    'profile.enter_vrc_password': "'请输入 VRChat 密码'",
    'profile.verifying': "'验证中...'",
    'profile.bind_success': "'绑定成功！'",
    'profile.login_first': "'请先登录'",
    'profile.gps_not_supported': "'您的浏览器不支持定位功能'",
    'profile.gps_getting': "'正在获取位置…'",
    'profile.gps_updated': "'位置已更新'",
    'profile.enter_passwords': "'请填写当前密码和新密码'",
    'profile.passwords_not_match': "'两次密码不一致'",
    'profile.change_failed': "'修改失败'",
    'profile.name_change_submitted': "'改名申请已提交'",
    'profile.loading': "'加载中...'",
    'profile.no_events': "'暂未报名任何活动'",
    'profile.load_failed': "'加载失败'",
    'profile.bind_failed': "'绑定失败'",
    'profile.pwd_change_failed': "'密码修改失败'",
    'profile.name_change_failed': "'改名失败'",
    'profile.vrc_bound': "'已绑定 VRChat'",
    # posts
    'posts.loading': "'加载中...'",
    'posts.load_failed': "'加载失败'",
    'posts.empty': "'还没有动态，来发布第一条'",
    'posts.comment_btn': "'💬 评论'",
    'posts.pin': "'📌 置顶'",
    'posts.delete': "'🗑️ 删除'",
    'posts.share_placeholder': "'分享你的日常...'",
    'posts.login_first': "'请先登录'",
    'posts.op_failed': "'操作失败'",
    'posts.comment_failed': "'评论失败'",
    'posts.deleted': "'已删除'",
    'posts.pinned': "'已置顶'",
    'posts.prev': "'‹ 上一张'",
    'posts.next': "'下一张 ›'",
    'posts.confirm_delete': "'确定删除此动态？'",
    'posts.confirm_delete_comment': "'确定删除此评论？'",
    'posts.unpinned': "'已取消置顶'",
    'posts.no_more': "'暂无更多动态'",
    # auth
    'auth.login_ok': "'登录成功'",
    'auth.login_failed': "'登录失败'",
    'auth.account_disabled': "'账号已被禁用'",
    'auth.session_expired': "'会话已过期'",
    'auth.enter_code': "'输入验证码'",
    'auth.send_code_first': "'请先发送验证码'",
    'auth.timeout_retry': "'请求超时，请重试'",
    'auth.vrc_login_ok': "'VRChat 登录成功'",
    'auth.network_error': "'网络错误'",
    'auth.logging_in': "'登录中...'",
    'auth.sending': "'发送中...'",
    'auth.send_code': "'发送验证码'",
    'auth.resend': "'重新发送'",
    'auth.login_ok_excl': "'登录成功！'",
    'auth.vrc_bound_hint': "'已绑定 VRChat，可直接使用 VRChat 登录'",
    'auth.login_failed_vrc': "'VRChat 登录失败'",
    # chat
    'chat.group_chat': "'👥 群聊'",
    'chat.dm': "'💬 私信'",
    'chat.no_history': "'暂无聊天记录'",
    'chat.first_message_emoji': "'发送第一条消息吧 👋'",
    'chat.group_start': "'群聊开始 👋'",
    'chat.create_group': "'➕ 创建群聊'",
    'chat.group_name': "'群聊名称'",
    'chat.select_members': "'选择成员'",
    'chat.back': "'← 返回'",
    'chat.share_location': "'📍 实时共享位置'",
    'chat.gps_not_supported': "'浏览器不支持定位'",
    'chat.gps_permission_denied': "'定位权限被拒'",
    'chat.gps_failed': "'获取位置失败'",
    'chat.location_stopped': "'已停止共享位置'",
    'chat.location_sharing': "'📍 位置共享'",
    'chat.location_started_msg': "'📍 我开启了实时位置共享'",
    'chat.location_stopped_msg': "'📍 已关闭实时位置共享'",
    'chat.user_no_location': "'该用户未开启位置共享'",
    'chat.gps_info_failed': "'获取位置信息失败'",
    'chat.create_ok': "'创建成功'",
    'chat.load_failed': "'加载失败'",
    # main
    'main.online_count': "'{n} 在线'",
    'main.unknown_user': "'未知用户'",
    'main.me': "'（我）'",
    'main.online': "'在线'",
    'main.online_users': "'🟢 当前在线'",
    'main.close': "'关闭'",
    'main.no_results': "'未找到相关结果'",
    'main.search_failed': "'搜索失败'",
    'main.upload_failed': "'上传失败'",
    'main.confirm_signup': "'确定报名此活动？'",
    'main.signup_failed': "'报名失败'",
    'main.confirm_cancel_signup': "'确定取消报名？'",
    'main.signup_cancelled': "'已取消报名'",
    'main.op_failed': "'操作失败'",
    'main.select_media': "'请选择图片或视频文件'",
    'main.uploading': "'上传中...'",
    'main.processing': "'处理中...'",
    'main.upload_ok': "'上传成功'",
    # map
    'map.load_failed': "'地图加载失败'",
    'map.load_failed_retry': "'⚠️ 地图加载失败，请刷新重试'",
    'map.send_message': "'💬 发消息'",
    'map.sharing_location': "'🟢 位置共享中'",
    'map.share_my_location': "'📍 共享我的位置'",
    'map.stop_sharing': "'🔴 停止共享'",
    'map.unknown_user': "'未知用户'",
    'map.no_world_events': "'暂无关联 World 的活动'",
    'map.unknown_world': "'未知世界'",
    'map.location_upload_failed': "'位置上传失败'",
    'map.location_fetch_failed': "'位置获取失败'",
    # birthday
    'birthday.no_birthdays': "'暂无生日信息'",
    'birthday.no_parties': "'暂无生日派对'",
    'birthday.create_party_prompt': "'创建生日派对活动？'",
    'birthday.party_title': "'🎂 的生日派对'",
    'birthday.celebrate': "'一起来庆祝吧！'",
    'birthday.create_failed': "'创建失败'",
    'birthday.party_updated': "'生日派对已更新'",
    'birthday.party_deleted': "'生日派对已删除'",
    'birthday.edit_party': "'✏️ 编辑生日派对'",
    'birthday.create_party': "'🎂 创建生日派对'",
    'birthday.confirm_delete_party': "'确定删除此生日派对？'",
    # announcements
    'announcements.no_announcements': "'暂无公告'",
    'announcements.pin': "'📌 置顶'",
    'announcements.public': "'🌐 公开'",
    'announcements.member_only': "'🔒 成员专属'",
    'announcements.modal_not_found': "'详情弹窗不在页面中'",
    'announcements.published_at': "'📅 发布于'",
    'announcements.edit': "'✏️ 编辑'",
    'announcements.delete': "'🗑️ 删除'",
    'announcements.edit_title': "'✏️ 编辑公告'",
    'announcements.publish_title': "'📢 发布公告'",
    'announcements.confirm_delete': "'确定删除此公告？'",
    # ui
    'ui.no_notifications': "'暂无通知'",
    'ui.delete': "'删除'",
    'ui.all_read': "'已全部标记已读'",
    'ui.op_failed': "'操作失败'",
    'ui.delete_failed': "'删除失败'",
    'ui.confirm_clear_notifications': "'确定清空所有通知？此操作不可恢复'",
    'ui.notifications_cleared': "'已清空所有通知'",
    'ui.weak': "'弱'",
    'ui.medium': "'中'",
    'ui.strong': "'强'",
    'ui.very_strong': "'非常强'",
    'ui.pwd_match': "'✅ 密码一致'",
    'ui.pwd_not_match': "'❌ 密码不一致'",
    'ui.theme_reset': "'主题已重置为默认'",
    # members
    'members.no_members': "'暂无成员'",
    'members.location': "'📍 位置'",
    'members.card': "'👤 名片'",
    'members.vrc': "'🎮 VRChat：'",
    'members.joined': "'📅 加入：'",
    'members.n_events': "'{n} 个活动'",
    'members.n_photos': "'{n} 张照片'",
    'members.edit_profile': "'✏️ 编辑资料'",
    'members.full_profile': "'📋 完整资料'",
    'members.loading_events': "'正在加载该用户的活动...'",
    'members.loading_photos': "'正在加载该用户的照片...'",
    # init
    'init.fill_id_pwd': "'请填写登录ID和密码'",
    'init.pwds_not_match': "'两次密码输入不一致'",
    'init.pwd_weak': "'密码强度不足（需至少8位，含大小写字母、数字、特殊字符）'",
    'init.create_ok': "'超级管理员创建成功！正在登录...'",
    'init.init_failed': "'初始化失败'",
    'init.init_req_failed': "'初始化请求失败'",
    # upload
    'upload_cancelled': "'上传已取消'",
    'upload_timeout': "'上传超时'",
}

# Build insert text
lines = []
for k in sorted(keys.keys()):
    lines.append(f"    '{k}': {keys[k]},")
key_block = '\n' + '\n'.join(lines)

# Find zh block end
locales_start = content.find('LOCALES = {')
zh_end = content.find('\n  },\n', locales_start + 20)
content = content[:zh_end] + key_block + content[zh_end:]

with open(I18N_FILE, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

open_c = content.count('{')
close_c = content.count('}')
print(f'✅ 已向 zh 块添加 {len(keys)} 个键')
print(f'大括号: {{ = {open_c} }} = {close_c} {"✅" if open_c == close_c else "❌"}')
