import os

lang_dir = r"d:\phpstudy_pro\WWW\jingtu-web\public\js\languages"

# Comprehensive missing translation keys
missing_keys_zh = {
    # achievements
    'achievements.locked': '未解锁',
    
    # admin
    'admin.approve': '批准',
    'admin.approve_confirm': '确定批准此申请？',
    'admin.approved': '已批准',
    'admin.ban_confirm': '确定封禁该用户？',
    'admin.banned': '已封禁',
    'admin.db_refresh': '刷新',
    'admin.enter_auth_code': '请输入验证码',
    'admin.enter_email_code': '请输入邮箱验证码',
    'admin.fill_display_name': '请填写显示名称',
    'admin.fill_login_pwd': '请填写登录密码',
    'admin.fill_vrc_account': '请填写VRChat账号',
    'admin.no_pending_requests': '暂无待审核请求',
    'admin.pending_review': '待审核',
    'admin.perm_album': '相册管理',
    'admin.perm_announce': '公告管理',
    'admin.perm_events': '活动管理',
    'admin.perm_group_images': '群组图片',
    'admin.perm_log': '操作日志',
    'admin.perm_name_change': '改名审核',
    'admin.perm_permissions': '权限管理',
    'admin.perm_roster': '成员管理',
    'admin.perm_users': '用户管理',
    'admin.perm_vrc_sync': 'VRC同步',
    'admin.reject': '拒绝',
    'admin.settings_saved': '设置已保存',
    'admin.unban_confirm': '确定解封该用户？',
    'admin.user_delete_confirm': '确定删除该用户？',
    'admin.vrc_syncing': '正在同步...',
    
    # admin_perms
    'admin_perms.delete_group_confirm_full': '确定删除此权限组？所有关联权限将丢失！',
    'admin_perms.inherited_from': '继承自',
    'admin_perms.perm_change_password': '修改密码',
    'admin_perms.perm_comment_event': '评论活动',
    'admin_perms.perm_create_album': '创建相册',
    'admin_perms.perm_create_album_category': '创建相册分类',
    'admin_perms.perm_create_announcement': '创建公告',
    'admin_perms.perm_create_event': '创建活动',
    'admin_perms.perm_create_photo': '上传照片',
    'admin_perms.perm_create_post': '发布动态',
    'admin_perms.perm_delete_announcement': '删除公告',
    'admin_perms.perm_delete_event': '删除活动',
    'admin_perms.perm_delete_photo': '删除照片',
    'admin_perms.perm_delete_post': '删除动态',
    'admin_perms.perm_edit_announcement': '编辑公告',
    'admin_perms.perm_edit_event': '编辑活动',
    'admin_perms.perm_edit_profile': '编辑资料',
    'admin_perms.perm_like_post': '点赞',
    'admin_perms.perm_manage_album': '管理相册',
    'admin_perms.perm_manage_announcements': '管理公告',
    'admin_perms.perm_manage_events': '管理活动',
    'admin_perms.perm_manage_group_images': '管理群组图片',
    'admin_perms.perm_manage_roles': '管理角色',
    'admin_perms.perm_manage_rosters': '管理成员',
    'admin_perms.perm_sign_event': '报名活动',
    'admin_perms.perm_upload_group_image': '上传群组图片',
    'admin_perms.perm_view_album': '查看相册',
    'admin_perms.perm_view_events': '查看活动',
    'admin_perms.perm_view_map': '查看地图',
    'admin_perms.perm_view_members': '查看成员',
    'admin_perms.permissions_label': '权限列表',
    
    # admin_users
    'admin_users.colon': ':',
    'admin_users.semicolon': ';',
    'admin_users.title_first_page': '第一页',
    'admin_users.title_last_page': '最后一页',
    
    # album
    'album.alt_photo': '照片',
    'album.delete_category_confirm': '确定删除此分类？所有照片将移至默认分类！',
    'album.delete_failed': '删除失败',
    'album.deleted_at': '删除时间',
    'album.deleted_n': '已删除 {n} 张',
    'album.enter_indices': '请输入索引范围（如 1-5）',
    'album.load_failed': '加载失败',
    'album.permanent_delete_confirm': '确定永久删除？此操作不可撤销！',
    'album.upload_hint': '支持 JPG、PNG、GIF 格式，最大 5MB',
    
    # announcements
    'announcements.create_failed': '创建失败',
    'announcements.create_first': '创建第一条公告',
    'announcements.created': '已创建',
    'announcements.deleted': '已删除',
    'announcements.edit_at': '编辑于',
    'announcements.edit_failed': '编辑失败',
    'announcements.edit_title_suffix': '（已编辑）',
    'announcements.edited_at': '最后编辑',
    'announcements.load_failed': '加载失败',
    'announcements.publish_title_suffix': '（已发布）',
    'announcements.stay_tuned': '敬请期待',
    'announcements.title_content_required': '标题和内容不能为空',
    'announcements.updated': '已更新',
    
    # auth
    'auth.cooldown': '操作过于频繁，请稍后再试',
    
    # birthday
    'birthday.confirm_create_party': '确定为此生日创建派对活动？',
    'birthday.created': '已创建',
    'birthday.load_failed': '加载失败',
    'birthday.party_default': '生日派对',
    'birthday.party_desc': '为 {name} 庆祝生日！',
    'birthday.party_load_failed': '加载生日派对失败',
    'birthday.party_title_for': '{name} 的生日派对',
    'birthday.status_ended': '已结束',
    'birthday.status_ongoing': '进行中',
    'birthday.status_upcoming': '即将开始',
    'birthday.today': '今天',
    'birthday.user_no_birthday': '该用户未设置生日',
    'birthday.view_detail': '查看详情',
    
    # chat
    'chat.add_admin': '设为管理员',
    'chat.admin_added': '已设为管理员',
    'chat.admin_removed': '已撤销管理员',
    'chat.cancel_btn': '取消',
    'chat.close': '关闭',
    'chat.create_btn': '创建',
    'chat.create_failed': '创建失败',
    'chat.group_created': '群聊已创建',
    'chat.group_creator': '创建者',
    'chat.group_location_started': '{name} 开始共享位置',
    'chat.group_name_placeholder': '输入群聊名称',
    'chat.group_name_required': '群聊名称不能为空',
    'chat.group_settings': '群设置',
    'chat.kick': '踢出',
    'chat.kick_confirm': '确定踢出该成员？',
    'chat.kicked': '已踢出',
    'chat.leave_confirm': '确定退出群聊？',
    'chat.leave_group': '退出群聊',
    'chat.left_group': '已退出群聊',
    'chat.loading_group': '加载群聊中...',
    'chat.member_list': '成员列表',
    'chat.n_members_label': '{n} 名成员',
    'chat.no_messages': '暂无消息',
    'chat.op_failed': '操作失败',
    'chat.remove_admin': '撤销管理员',
    'chat.send_failed': '发送失败',
    'chat.stop_sharing': '停止共享',
    
    # checkin
    'checkin.already_checked_in': '今日已签到',
    'checkin.checkin': '签到',
    'checkin.checking': '签到中...',
    'checkin.current_streak': '连续签到',
    'checkin.days': '天',
    'checkin.error': '签到失败',
    'checkin.point': '积分',
    'checkin.points': '积分',
    'checkin.rewards': '奖励',
    'checkin.title': '签到',
    'checkin.today_checked': '今日已签到',
    'checkin.total_checkins': '总签到',
    
    # core
    'core.cancel_btn': '取消',
    'core.confirm_btn': '确定',
    
    # dashboard
    'dashboard.checkins': '签到',
    'dashboard.events': '活动',
    'dashboard.members': '成员',
    'dashboard.online': '在线',
    'dashboard.photos': '照片',
    'dashboard.posts': '动态',
    
    # events
    'events.about_to_start': '即将开始',
    'events.after_start': '开始后',
    'events.aria_close': '关闭',
    'events.back_to_today': '返回今天',
    'events.checkin_now': '立即签到',
    'events.date_format': 'YYYY-MM-DD HH:mm',
    'events.day_suffix': '日',
    'events.days': '天',
    'events.edit_event': '编辑活动',
    'events.edit_party': '编辑派对',
    'events.hours': '小时',
    'events.limit': '限制',
    'events.login_to_sign': '请先登录后报名',
    'events.mark_all_checkin': '标记全员签到',
    'events.max_people': '最多人数',
    'events.member_only_tag': '仅限成员',
    'events.minutes': '分钟',
    'events.month_': '月',
    'events.n_checked_in': '{n} 人已签到',
    'events.no_archive': '暂无归档活动',
    'events.no_sign_ins': '暂无报名',
    'events.or_manual_checkin': '或手动签到',
    'events.scan_to_checkin': '扫码签到',
    'events.sign_in_failed': '签到失败',
    'events.sign_in_recorded': '已记录签到',
    'events.status_ongoing_or_not_started': '进行中/未开始',
    'events.stay_tuned': '敬请期待',
    'events.weekday_fri': '周五',
    'events.weekday_mon': '周一',
    'events.weekday_sat': '周六',
    'events.weekday_sun': '周日',
    'events.weekday_thu': '周四',
    'events.weekday_tue': '周二',
    'events.weekday_wed': '周三',
    
    # global
    'global.avatar': '头像',
    'global.banner': '横幅',
    'global.category_announce': '公告',
    'global.category_event': '活动',
    'global.category_member': '成员',
    'global.cover': '封面',
    'global.upload_select_images': '选择图片',
    'global.video_uploaded': '视频已上传',
    
    # group
    'group.bind_first': '请先绑定VRChat账号',
    'group.just_now': '刚刚',
    'group.load_failed': '加载失败',
    'group.no_data': '暂无数据',
    'group.no_offline': '暂无离线成员',
    'group.no_online': '暂无在线成员',
    'group.stats_updated': '统计已更新',
    
    # main
    'main.group_updated': '群组已更新',
    'main.photo_uploaded': '照片已上传',
    
    # map
    'map.n_events': '{n} 个活动',
    'map.unknown_location': '未知位置',
    
    # members
    'members.detail_load_failed': '加载详情失败',
    'members.found_count': '找到 {n} 位成员',
    'members.load_failed_msg': '加载成员列表失败',
    'members.total_count': '共 {n} 位成员',
    
    # notification
    'notification.comment_event': '{name} 评论了活动',
    'notification.comment_photo': '{name} 评论了照片',
    'notification.comment_post': '{name} 评论了动态',
    'notification.event_reminder': '活动即将开始',
    'notification.like_photo': '{name} 点赞了照片',
    'notification.like_post': '{name} 点赞了动态',
    'notification.name_change_approved': '改名申请已通过',
    'notification.name_change_rejected': '改名申请被拒绝',
    'notification.reply_comment': '{name} 回复了评论',
    'notification.sign_event': '{name} 报名了活动',
    
    # notifications
    'notifications.browser': '浏览器通知',
    'notifications.email': '邮件通知',
    'notifications.settings': '通知设置',
    'notifications.sound': '通知音效',
    
    # posts
    'posts.add_media_btn': '添加图片/视频',
    'posts.all_comments_title': '全部评论',
    'posts.alt_image': '图片',
    'posts.cancel_btn': '取消',
    'posts.content_required': '内容不能为空',
    'posts.create_post_title': '发布动态',
    'posts.created': '已发布',
    'posts.detail_title': '动态详情',
    'posts.image': '图片',
    'posts.like_btn': '点赞',
    'posts.liked_btn': '已赞',
    'posts.placeholder': '分享你的想法...',
    'posts.publish_btn': '发布',
    'posts.send_btn': '发送',
    'posts.text': '文字',
    'posts.toggle_pin': '置顶',
    'posts.unliked_btn': '取消赞',
    'posts.user': '用户',
    'posts.video': '视频',
    'posts.video_load_failed': '视频加载失败',
    'posts.view_all_comments': '查看全部评论',
    'posts.visibility_member': '成员可见',
    'posts.visibility_private': '仅自己可见',
    'posts.visibility_public': '公开',
    
    # profile
    'profile.enable_gps': '启用定位',
    'profile.gps_accuracy': '定位精度',
    'profile.gps_check_failed': '定位检查失败',
    'profile.gps_timeout': '定位超时',
    'profile.motto_empty': '个性签名不能为空',
    'profile.no_changes': '没有修改内容',
    'profile.pwd_changed': '密码已修改',
    'profile.vrc_not_bound': '未绑定VRChat',
    'profile.vrc_unbind_confirm': '确定解绑VRChat账号？',
    
    # profile_page
    'profile_page.bio_empty': '个人简介不能为空',
    'profile_page.create_first_album': '创建第一个相册',
    'profile_page.invalid_id': '无效的用户ID',
    'profile_page.n_albums': '{n} 个相册',
    'profile_page.n_photos': '{n} 张照片',
    'profile_page.n_videos': '{n} 个视频',
    'profile_page.new_album_btn': '新建相册',
    'profile_page.no_album': '暂无相册',
    'profile_page.no_public_album': '暂无公开相册',
    'profile_page.no_public_video': '暂无公开视频',
    'profile_page.no_video': '暂无视频',
    'profile_page.not_found': '用户不存在',
    'profile_page.unnamed_album': '未命名相册',
    'profile_page.uploaded_n': '已上传 {n} 个文件',
    'profile_page.uploading_video': '视频上传中...',
    
    # settings
    'settings.allow_register': '允许注册',
    'settings.animation_fade': '淡入淡出',
    'settings.animation_none': '无动画',
    'settings.animation_slide': '滑动',
    'settings.contact_email': '联系邮箱',
    'settings.hero_accent_color': '强调色',
    'settings.hero_animation': '背景动画',
    'settings.hero_badge_text': '徽章文字',
    'settings.hero_bg_color': '背景颜色',
    'settings.hero_bg_url': '背景图片',
    'settings.hero_decor': '装饰元素',
    'settings.hero_desc': '描述文字',
    'settings.hero_overlay_opacity': '遮罩透明度',
    'settings.hero_show_badge': '显示徽章',
    'settings.hero_show_stats': '显示统计',
    'settings.hero_subtitle': '副标题',
    'settings.hero_title': '标题',
    'settings.hide': '隐藏',
    'settings.max_upload': '最大上传大小',
    'settings.post_max_images': '动态最大图片数',
    'settings.post_max_videos': '动态最大视频数',
    'settings.post_video_max_size': '视频最大大小',
    'settings.posts_per_page': '每页动态数',
    'settings.require_approval': '需审核',
    'settings.save': '保存设置',
    'settings.show': '显示',
    'settings.site_name': '站点名称',
    'settings.site_notice': '站点公告',
    'settings.video_size': '视频尺寸',
    
    # theme
    'theme.brightness': '亮度',
    'theme.close': '关闭',
    'theme.color': '颜色',
    'theme.manual': '手动',
    'theme.mode': '模式',
    'theme.settings': '主题设置',
    'theme.system': '跟随系统',
    'theme.time': '定时切换',
    
    # ui
    'ui.load_failed': '加载失败',
    
    # vrc
    'vrc.code_error': '验证码错误',
    'vrc.enter_code': '请输入验证码',
    'vrc.enter_keyword': '请输入关键词',
    'vrc.login_success': '登录成功',
    'vrc.not_bound': '未绑定',
    'vrc.search_failed': '搜索失败',
    'vrc.verify_failed': '验证失败',
}

# English translations
missing_keys_en = {
    # achievements
    'achievements.locked': 'Locked',
    
    # admin
    'admin.approve': 'Approve',
    'admin.approve_confirm': 'Are you sure you want to approve this request?',
    'admin.approved': 'Approved',
    'admin.ban_confirm': 'Are you sure you want to ban this user?',
    'admin.banned': 'Banned',
    'admin.db_refresh': 'Refresh',
    'admin.enter_auth_code': 'Enter verification code',
    'admin.enter_email_code': 'Enter email verification code',
    'admin.fill_display_name': 'Enter display name',
    'admin.fill_login_pwd': 'Enter login password',
    'admin.fill_vrc_account': 'Enter VRChat account',
    'admin.no_pending_requests': 'No pending requests',
    'admin.pending_review': 'Pending Review',
    'admin.perm_album': 'Album Management',
    'admin.perm_announce': 'Announcement Management',
    'admin.perm_events': 'Event Management',
    'admin.perm_group_images': 'Group Images',
    'admin.perm_log': 'Operation Log',
    'admin.perm_name_change': 'Name Change Review',
    'admin.perm_permissions': 'Permission Management',
    'admin.perm_roster': 'Roster Management',
    'admin.perm_users': 'User Management',
    'admin.perm_vrc_sync': 'VRC Sync',
    'admin.reject': 'Reject',
    'admin.settings_saved': 'Settings saved',
    'admin.unban_confirm': 'Are you sure you want to unban this user?',
    'admin.user_delete_confirm': 'Are you sure you want to delete this user?',
    'admin.vrc_syncing': 'Syncing...',
    
    # admin_perms
    'admin_perms.delete_group_confirm_full': 'Are you sure you want to delete this permission group? All associated permissions will be lost!',
    'admin_perms.inherited_from': 'Inherited from',
    'admin_perms.perm_change_password': 'Change Password',
    'admin_perms.perm_comment_event': 'Comment Events',
    'admin_perms.perm_create_album': 'Create Album',
    'admin_perms.perm_create_album_category': 'Create Album Category',
    'admin_perms.perm_create_announcement': 'Create Announcement',
    'admin_perms.perm_create_event': 'Create Event',
    'admin_perms.perm_create_photo': 'Upload Photo',
    'admin_perms.perm_create_post': 'Create Post',
    'admin_perms.perm_delete_announcement': 'Delete Announcement',
    'admin_perms.perm_delete_event': 'Delete Event',
    'admin_perms.perm_delete_photo': 'Delete Photo',
    'admin_perms.perm_delete_post': 'Delete Post',
    'admin_perms.perm_edit_announcement': 'Edit Announcement',
    'admin_perms.perm_edit_event': 'Edit Event',
    'admin_perms.perm_edit_profile': 'Edit Profile',
    'admin_perms.perm_like_post': 'Like',
    'admin_perms.perm_manage_album': 'Manage Albums',
    'admin_perms.perm_manage_announcements': 'Manage Announcements',
    'admin_perms.perm_manage_events': 'Manage Events',
    'admin_perms.perm_manage_group_images': 'Manage Group Images',
    'admin_perms.perm_manage_roles': 'Manage Roles',
    'admin_perms.perm_manage_rosters': 'Manage Rosters',
    'admin_perms.perm_sign_event': 'Sign Event',
    'admin_perms.perm_upload_group_image': 'Upload Group Image',
    'admin_perms.perm_view_album': 'View Album',
    'admin_perms.perm_view_events': 'View Events',
    'admin_perms.perm_view_map': 'View Map',
    'admin_perms.perm_view_members': 'View Members',
    'admin_perms.permissions_label': 'Permissions',
    
    # admin_users
    'admin_users.colon': ':',
    'admin_users.semicolon': ';',
    'admin_users.title_first_page': 'First Page',
    'admin_users.title_last_page': 'Last Page',
    
    # album
    'album.alt_photo': 'Photo',
    'album.delete_category_confirm': 'Are you sure you want to delete this category? All photos will be moved to default!',
    'album.delete_failed': 'Delete failed',
    'album.deleted_at': 'Deleted At',
    'album.deleted_n': 'Deleted {n} items',
    'album.enter_indices': 'Enter index range (e.g. 1-5)',
    'album.load_failed': 'Load failed',
    'album.permanent_delete_confirm': 'Are you sure you want to permanently delete? This cannot be undone!',
    'album.upload_hint': 'Supports JPG, PNG, GIF. Max 5MB',
    
    # announcements
    'announcements.create_failed': 'Create failed',
    'announcements.create_first': 'Create first announcement',
    'announcements.created': 'Created',
    'announcements.deleted': 'Deleted',
    'announcements.edit_at': 'Edited at',
    'announcements.edit_failed': 'Edit failed',
    'announcements.edit_title_suffix': ' (Edited)',
    'announcements.edited_at': 'Last edited',
    'announcements.load_failed': 'Load failed',
    'announcements.publish_title_suffix': ' (Published)',
    'announcements.stay_tuned': 'Stay tuned',
    'announcements.title_content_required': 'Title and content cannot be empty',
    'announcements.updated': 'Updated',
    
    # auth
    'auth.cooldown': 'Too many requests, please try again later',
    
    # birthday
    'birthday.confirm_create_party': 'Create a birthday party for this birthday?',
    'birthday.created': 'Created',
    'birthday.load_failed': 'Load failed',
    'birthday.party_default': 'Birthday Party',
    'birthday.party_desc': 'Celebrate {name} birthday!',
    'birthday.party_load_failed': 'Failed to load birthday party',
    'birthday.party_title_for': '{name} Birthday Party',
    'birthday.status_ended': 'Ended',
    'birthday.status_ongoing': 'Ongoing',
    'birthday.status_upcoming': 'Upcoming',
    'birthday.today': 'Today',
    'birthday.user_no_birthday': 'User has not set birthday',
    'birthday.view_detail': 'View Details',
    
    # chat
    'chat.add_admin': 'Make Admin',
    'chat.admin_added': 'Made admin',
    'chat.admin_removed': 'Removed admin',
    'chat.cancel_btn': 'Cancel',
    'chat.close': 'Close',
    'chat.create_btn': 'Create',
    'chat.create_failed': 'Create failed',
    'chat.group_created': 'Group chat created',
    'chat.group_creator': 'Creator',
    'chat.group_location_started': '{name} started sharing location',
    'chat.group_name_placeholder': 'Enter group name',
    'chat.group_name_required': 'Group name is required',
    'chat.group_settings': 'Group Settings',
    'chat.kick': 'Kick',
    'chat.kick_confirm': 'Are you sure you want to kick this member?',
    'chat.kicked': 'Kicked',
    'chat.leave_confirm': 'Are you sure you want to leave?',
    'chat.leave_group': 'Leave Group',
    'chat.left_group': 'Left group',
    'chat.loading_group': 'Loading group...',
    'chat.member_list': 'Members',
    'chat.n_members_label': '{n} members',
    'chat.no_messages': 'No messages',
    'chat.op_failed': 'Operation failed',
    'chat.remove_admin': 'Remove Admin',
    'chat.send_failed': 'Send failed',
    'chat.stop_sharing': 'Stop sharing',
    
    # checkin
    'checkin.already_checked_in': 'Already checked in today',
    'checkin.checkin': 'Check In',
    'checkin.checking': 'Checking in...',
    'checkin.current_streak': 'Current Streak',
    'checkin.days': 'days',
    'checkin.error': 'Check-in failed',
    'checkin.point': 'Point',
    'checkin.points': 'Points',
    'checkin.rewards': 'Rewards',
    'checkin.title': 'Check In',
    'checkin.today_checked': 'Checked in today',
    'checkin.total_checkins': 'Total Check-ins',
    
    # core
    'core.cancel_btn': 'Cancel',
    'core.confirm_btn': 'Confirm',
    
    # dashboard
    'dashboard.checkins': 'Check-ins',
    'dashboard.events': 'Events',
    'dashboard.members': 'Members',
    'dashboard.online': 'Online',
    'dashboard.photos': 'Photos',
    'dashboard.posts': 'Posts',
    
    # events
    'events.about_to_start': 'About to start',
    'events.after_start': 'After start',
    'events.aria_close': 'Close',
    'events.back_to_today': 'Back to today',
    'events.checkin_now': 'Check-in now',
    'events.date_format': 'YYYY-MM-DD HH:mm',
    'events.day_suffix': '',
    'events.days': 'days',
    'events.edit_event': 'Edit Event',
    'events.edit_party': 'Edit Party',
    'events.hours': 'hours',
    'events.limit': 'Limit',
    'events.login_to_sign': 'Please login to sign up',
    'events.mark_all_checkin': 'Mark all checked-in',
    'events.max_people': 'Max participants',
    'events.member_only_tag': 'Members only',
    'events.minutes': 'minutes',
    'events.month_': 'Month',
    'events.n_checked_in': '{n} checked in',
    'events.no_archive': 'No archived events',
    'events.no_sign_ins': 'No sign-ups',
    'events.or_manual_checkin': 'or manual check-in',
    'events.scan_to_checkin': 'Scan to check-in',
    'events.sign_in_failed': 'Sign-in failed',
    'events.sign_in_recorded': 'Sign-in recorded',
    'events.status_ongoing_or_not_started': 'Ongoing/Not started',
    'events.stay_tuned': 'Stay tuned',
    'events.weekday_fri': 'Fri',
    'events.weekday_mon': 'Mon',
    'events.weekday_sat': 'Sat',
    'events.weekday_sun': 'Sun',
    'events.weekday_thu': 'Thu',
    'events.weekday_tue': 'Tue',
    'events.weekday_wed': 'Wed',
    
    # global
    'global.avatar': 'Avatar',
    'global.banner': 'Banner',
    'global.category_announce': 'Announcement',
    'global.category_event': 'Event',
    'global.category_member': 'Member',
    'global.cover': 'Cover',
    'global.upload_select_images': 'Select images',
    'global.video_uploaded': 'Video uploaded',
    
    # group
    'group.bind_first': 'Please bind VRChat account first',
    'group.just_now': 'Just now',
    'group.load_failed': 'Load failed',
    'group.no_data': 'No data',
    'group.no_offline': 'No offline members',
    'group.no_online': 'No online members',
    'group.stats_updated': 'Stats updated',
    
    # main
    'main.group_updated': 'Group updated',
    'main.photo_uploaded': 'Photo uploaded',
    
    # map
    'map.n_events': '{n} events',
    'map.unknown_location': 'Unknown location',
    
    # members
    'members.detail_load_failed': 'Failed to load details',
    'members.found_count': 'Found {n} members',
    'members.load_failed_msg': 'Failed to load members',
    'members.total_count': '{n} members',
    
    # notification
    'notification.comment_event': '{name} commented on an event',
    'notification.comment_photo': '{name} commented on a photo',
    'notification.comment_post': '{name} commented on a post',
    'notification.event_reminder': 'Event starting soon',
    'notification.like_photo': '{name} liked a photo',
    'notification.like_post': '{name} liked a post',
    'notification.name_change_approved': 'Name change approved',
    'notification.name_change_rejected': 'Name change rejected',
    'notification.reply_comment': '{name} replied to your comment',
    'notification.sign_event': '{name} signed up for an event',
    
    # notifications
    'notifications.browser': 'Browser Notifications',
    'notifications.email': 'Email Notifications',
    'notifications.settings': 'Notification Settings',
    'notifications.sound': 'Notification Sound',
    
    # posts
    'posts.add_media_btn': 'Add photo/video',
    'posts.all_comments_title': 'All Comments',
    'posts.alt_image': 'Image',
    'posts.cancel_btn': 'Cancel',
    'posts.content_required': 'Content cannot be empty',
    'posts.create_post_title': 'Create Post',
    'posts.created': 'Created',
    'posts.detail_title': 'Post Details',
    'posts.image': 'Image',
    'posts.like_btn': 'Like',
    'posts.liked_btn': 'Liked',
    'posts.placeholder': 'Share your thoughts...',
    'posts.publish_btn': 'Publish',
    'posts.send_btn': 'Send',
    'posts.text': 'Text',
    'posts.toggle_pin': 'Pin',
    'posts.unliked_btn': 'Unlike',
    'posts.user': 'User',
    'posts.video': 'Video',
    'posts.video_load_failed': 'Video load failed',
    'posts.view_all_comments': 'View all comments',
    'posts.visibility_member': 'Members only',
    'posts.visibility_private': 'Private',
    'posts.visibility_public': 'Public',
    
    # profile
    'profile.enable_gps': 'Enable GPS',
    'profile.gps_accuracy': 'GPS Accuracy',
    'profile.gps_check_failed': 'GPS check failed',
    'profile.gps_timeout': 'GPS timeout',
    'profile.motto_empty': 'Motto cannot be empty',
    'profile.no_changes': 'No changes',
    'profile.pwd_changed': 'Password changed',
    'profile.vrc_not_bound': 'Not bound to VRChat',
    'profile.vrc_unbind_confirm': 'Are you sure you want to unbind VRChat?',
    
    # profile_page
    'profile_page.bio_empty': 'Bio cannot be empty',
    'profile_page.create_first_album': 'Create first album',
    'profile_page.invalid_id': 'Invalid user ID',
    'profile_page.n_albums': '{n} albums',
    'profile_page.n_photos': '{n} photos',
    'profile_page.n_videos': '{n} videos',
    'profile_page.new_album_btn': 'New Album',
    'profile_page.no_album': 'No albums',
    'profile_page.no_public_album': 'No public albums',
    'profile_page.no_public_video': 'No public videos',
    'profile_page.no_video': 'No videos',
    'profile_page.not_found': 'User not found',
    'profile_page.unnamed_album': 'Unnamed Album',
    'profile_page.uploaded_n': 'Uploaded {n} files',
    'profile_page.uploading_video': 'Uploading video...',
    
    # settings
    'settings.allow_register': 'Allow Registration',
    'settings.animation_fade': 'Fade',
    'settings.animation_none': 'None',
    'settings.animation_slide': 'Slide',
    'settings.contact_email': 'Contact Email',
    'settings.hero_accent_color': 'Accent Color',
    'settings.hero_animation': 'Background Animation',
    'settings.hero_badge_text': 'Badge Text',
    'settings.hero_bg_color': 'Background Color',
    'settings.hero_bg_url': 'Background Image',
    'settings.hero_decor': 'Decoration',
    'settings.hero_desc': 'Description',
    'settings.hero_overlay_opacity': 'Overlay Opacity',
    'settings.hero_show_badge': 'Show Badge',
    'settings.hero_show_stats': 'Show Stats',
    'settings.hero_subtitle': 'Subtitle',
    'settings.hero_title': 'Title',
    'settings.hide': 'Hide',
    'settings.max_upload': 'Max Upload Size',
    'settings.post_max_images': 'Max Images per Post',
    'settings.post_max_videos': 'Max Videos per Post',
    'settings.post_video_max_size': 'Max Video Size',
    'settings.posts_per_page': 'Posts per Page',
    'settings.require_approval': 'Require Approval',
    'settings.save': 'Save Settings',
    'settings.show': 'Show',
    'settings.site_name': 'Site Name',
    'settings.site_notice': 'Site Notice',
    'settings.video_size': 'Video Size',
    
    # theme
    'theme.brightness': 'Brightness',
    'theme.close': 'Close',
    'theme.color': 'Color',
    'theme.manual': 'Manual',
    'theme.mode': 'Mode',
    'theme.settings': 'Theme Settings',
    'theme.system': 'System',
    'theme.time': 'Schedule',
    
    # ui
    'ui.load_failed': 'Load failed',
    
    # vrc
    'vrc.code_error': 'Code error',
    'vrc.enter_code': 'Enter code',
    'vrc.enter_keyword': 'Enter keyword',
    'vrc.login_success': 'Login successful',
    'vrc.not_bound': 'Not bound',
    'vrc.search_failed': 'Search failed',
    'vrc.verify_failed': 'Verification failed',
}

def add_keys_to_file(filepath, keys_dict):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    new_keys = []
    for key, value in keys_dict.items():
        if key not in content:
            new_keys.append(f"    '{key}': '{value}',")
    
    if new_keys:
        close_brace_idx = content.rfind('};')
        if close_brace_idx != -1:
            insert_pos = close_brace_idx
            new_content = content[:insert_pos] + '\n' + '\n'.join(new_keys) + '\n' + content[insert_pos:]
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f"Added {len(new_keys)} keys to {os.path.basename(filepath)}")
        else:
            print(f"Could not find closing brace in {os.path.basename(filepath)}")
    else:
        print(f"No new keys to add to {os.path.basename(filepath)}")

add_keys_to_file(os.path.join(lang_dir, 'zh.js'), missing_keys_zh)
add_keys_to_file(os.path.join(lang_dir, 'en.js'), missing_keys_en)

print("\nDone!")
